define mod: libs

mod{*}:
{
  bin.lib.prefix = mod_

  # Install into the libnp-mod/ subdirectory of, say, /usr/libexec/
  #
  install = /usr/libexec/
}

intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.

mod{np}: {hxx ixx txx cxx}{**} \
         $impl_libs $intf_libs

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root"

# The httpd package does not provide pkg-config metadata, so we specify the
# header directory explicitly.
#
cxx.poptions =+ "-I/usr/include/httpd"

# Don't install any of the module's headers.
#
{hxx ixx txx}{*}:
{
  install.subdirs = false
}
